### ISSUE TITLE
There is no .envrc.example file 

### ISSUE THREAD

**Issue by toledoroy** [turbo-eth/turbo-eth#1]
The readme says copy the .envrc.example file, but file is missing from the repo.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/5618090/174945035-96a02466-45a3-4b85-b142-291427644533.png">

**Comment by kamescg** [comment]
good catch @toledoroy. will add in these .envrc.example this week.

also thinking about moving away from `direnv` since most developers will probably not have it installed by default. if you have any thoughts about this, would love to hear.

**Comment by wottpal** [comment]
i would agree with that decision. it's a cool tool. but lowering the necessity of pre-installed things is a good thing!

**Comment by toledoroy** [comment]
Sure. If you don't need it then don't use it :)

**Comment by kamescg** [comment]
Fixed in #8
